name: geobook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - rioxarray=0.22.0
  - geopandas=1.1.4
  - ipykernel=7.0.1
  - planetary-computer=1.0.0
  - fiona=1.10.1
  - odc-stac=0.5.2
  - geemap=0.38.3
  - poetry
  - gdal=3.12.3